# FractionsDebug

hacks. sometimes it if faster to debug using a REPL

In [1]:
# # import fractions as fr
# from fractions import 

# use display() to print an html version of a data frame
# useful if dataFrame output is not generated by last like of cell
from IPython.display import display, Image

import os
import numpy as np
import pandas as pd

import sys

In [2]:
# to be able to import our local python files we need to set the sys.path
# https://stackoverflow.com/a/50155834
sys.path.append(os.getcwd() + '/../python/')
print("\nsys.path:\n{}\n".format(sys.path))

sys.path:
['/private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/jupyterNotebooks', '/private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/jupyterNotebooks', '/private/home/aedavids/extraCellularRNA/src', '/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python311.zip', '/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python3.11', '/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python3.11/lib-dynload', '', '/private/home/aedavids/miniconda3/envs/extraCellularRNA/lib/python3.11/site-packages', '/private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/jupyterNotebooks/../python/']

In [3]:
from analysis.fractions import CibersortResultsAsKWayClassifier

In [4]:
!ls ../python

analysis  pipeline

In [5]:
! ls ../python/analysis/test/data

expectedFractions.tsv  results.tsv

In [6]:
dataDir = "../python/analysis/test/data"
expectedFractionsPath = f'{dataDir}/expectedFractions.tsv'
resultPath            = f'{dataDir}/results.tsv'

In [7]:
evaluator = CibersortResultsAsKWayClassifier(resultPath, expectedFractionsPath, verbose=True)

expectedFractionsDF.shape: (8, 11)
cibersortFractionsDF.shape: (8, 9)
predictionsDF.shape: (8, 8)
confusionDF.shape: (8, 19)

In [8]:
# ORIG_PYTHONPATH = os.environ['PYTHONPATH']

In [9]:
# fr.CibersortResultsAsKWayClassifier()

In [10]:
trueLabelDict = {
's1' : 'BBB',
's2' : 'AAA',
's3' : 'CCC',
's4' : 'BBB',
's5':'BBB',
's6': 'CCC'}

trueLabels = pd.Series(trueLabelDict, name="Mixture")
trueLabels.index.name = "aedwip"
trueLabels

aedwip
s1    BBB
s2    AAA
s3    CCC
s4    BBB
s5    BBB
s6    CCC
Name: Mixture, dtype: object

In [11]:
predictedLabeslDict = {
's1' : 'AAA',
's2' : 'AAA',
's3' : 'CCC',
's4' : 'BBB',
's5' : 'BBB',
's6' : 'CCC'
}

predictedLabels = pd.Series(predictedLabeslDict, name="Mixture")
predictedLabels

s1    AAA
s2    AAA
s3    CCC
s4    BBB
s5    BBB
s6    CCC
Name: Mixture, dtype: object

In [12]:
a = ["a", "x", "n"]
b = ["b", "x"]
sorted( list( set(a + b) ) )

['a', 'b', 'n', 'x']

In [13]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
a = np.array([1,2,5,3])
b = np.array([6,2])
np.sort( np.unique(np.concatenate( (a, b) )) )

array([1, 2, 3, 5, 6])

In [15]:
# transpose signature bug

In [16]:
# [signatureDF
#                           g1    g2    g3
# category                                
# Adipose_Subcutaneous     1.0   1.0   1.0
# Artery_Tibial            4.0   4.0   4.0
# Breast_Mammary_Tissue   20.5  20.5  20.5
# Heart_Atrial_Appendage   9.0   9.0   9.0]

dataDict = {
            'g1' : [1.0, 4.0, 20.5, 9.0],
            'g2' : [1.0, 4.0, 20.5, 9.0],
            'g3' : [1.0, 4.0, 20.5, 9.0] }

signatureDF = pd.DataFrame(dataDict, 
                           index=["Adipose_Subcutaneous", "Artery_Tibial", 
                                  "Breast_Mammary_Tissue", "Heart_Atrial_Appendage"]

                          )

signatureDF.name

AttributeError: 'DataFrame' object has no attribute 'name'

In [ ]:

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Alice", "Bob", "Alice", "Bob"],
    "Subject": ["Math", "Math", "Science", "Science", "English", "English"],
    "Score": [90, 80, 95, 85, 92, 87]
})

grouped = df.groupby("Name")
print(grouped)
print(type(grouped))

In [ ]:
transposed = grouped.apply(lambda x: x.set_index("Subject")["Score"].T)
transposed

In [ ]:
list(transposed.index)

In [ ]:
values = np.array([[ 1. ,  1. ,  1. ],
       [ 4. ,  4. ,  4. ],
       [20.5, 20.5, 20.5],
       [ 9. ,  9. ,  9. ]])

signatureIndices = ['Adipose_Subcutaneous', 'Artery_Tibial', 'Breast_Mammary_Tissue', 'Heart_Atrial_Appendage']

signatureCols = ['g1', 'g2', 'g3']

hackDF = pd.DataFrame(data=values, columns=signatureCols, index= signatureIndices)

hackDF.index.name = "name"

hackDF

In [35]:

groupedByGeneDict = {'geneId': {0: 'g0', 1: 'g1', 2: 'g2', 3: 'g3', 4: 'g4', 5: 'g5', 6: 'g6', 7: 'g7', 8: 'g8'}, 
                     'GTEX-1117F-0226-SM-5GZZ7': {0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1}, 
                     'GTEX-1117F-0526-SM-5EGHJ': {0: 2, 1: 2, 2: 2, 3: 2, 4: 2, 5: 2, 6: 2, 7: 2, 8: 2}, 
                     'GTEX-1117F-0726-SM-5GIEN': {0: 3, 1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3, 7: 3, 8: 3},
                     'GTEX-1117F-2826-SM-5GZXL': {0: 4, 1: 4, 2: 4, 3: 4, 4: 4, 5: 4, 6: 4, 7: 4, 8: 4}, 
                     'GTEX-1117F-2826-SM-5GZXX': {0: 5, 1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5}}
scalingFactorDict = {'sizeFactors(dds)': {0: 1.0, 1: 2.0, 2: 3.0, 3: 4.0, 4: 5.0}}

groupDF = pd.DataFrame(groupedByGeneDict)
display(groupDF)

scalingFactorDF = pd.DataFrame(scalingFactorDict)
scalingFactorDF

,geneId,GTEX-1117F-0226-SM-5GZZ7,GTEX-1117F-0526-SM-5EGHJ,GTEX-1117F-0726-SM-5GIEN,GTEX-1117F-2826-SM-5GZXL,GTEX-1117F-2826-SM-5GZXX
0,g0,1,2,3,4,5
1,g1,1,2,3,4,5
2,g2,1,2,3,4,5
3,g3,1,2,3,4,5
4,g4,1,2,3,4,5
5,g5,1,2,3,4,5
6,g6,1,2,3,4,5
7,g7,1,2,3,4,5
8,g8,1,2,3,4,5

   sizeFactors(dds)
0               1.0
1               2.0
2               3.0
3               4.0
4               5.0

In [31]:
cols = list(groupDF.columns)#.remove('geneId')
cols.remove('geneId')
print(cols)

countsDF = groupDF.loc[:,cols]
display(countsDF)

print()

['GTEX-1117F-0226-SM-5GZZ7', 'GTEX-1117F-0526-SM-5EGHJ', 'GTEX-1117F-0726-SM-5GIEN', 'GTEX-1117F-2826-SM-5GZXL', 'GTEX-1117F-2826-SM-5GZXX']

,GTEX-1117F-0226-SM-5GZZ7,GTEX-1117F-0526-SM-5EGHJ,GTEX-1117F-0726-SM-5GIEN,GTEX-1117F-2826-SM-5GZXL,GTEX-1117F-2826-SM-5GZXX
0,1,2,3,4,5
1,1,2,3,4,5
2,1,2,3,4,5
3,1,2,3,4,5
4,1,2,3,4,5
5,1,2,3,4,5
6,1,2,3,4,5
7,1,2,3,4,5
8,1,2,3,4,5

In [43]:
countsDF * scalingFactorDF.transpose().values

,GTEX-1117F-0226-SM-5GZZ7,GTEX-1117F-0526-SM-5EGHJ,GTEX-1117F-0726-SM-5GIEN,GTEX-1117F-2826-SM-5GZXL,GTEX-1117F-2826-SM-5GZXX
0,1.0,4.0,9.0,16.0,25.0
1,1.0,4.0,9.0,16.0,25.0
2,1.0,4.0,9.0,16.0,25.0
3,1.0,4.0,9.0,16.0,25.0
4,1.0,4.0,9.0,16.0,25.0
5,1.0,4.0,9.0,16.0,25.0
6,1.0,4.0,9.0,16.0,25.0
7,1.0,4.0,9.0,16.0,25.0
8,1.0,4.0,9.0,16.0,25.0

In [44]:
groupDF.loc[:,cols] = countsDF * scalingFactorDF.transpose().values
groupDF

,geneId,GTEX-1117F-0226-SM-5GZZ7,GTEX-1117F-0526-SM-5EGHJ,GTEX-1117F-0726-SM-5GIEN,GTEX-1117F-2826-SM-5GZXL,GTEX-1117F-2826-SM-5GZXX
0,g0,1,4,9,16,25
1,g1,1,4,9,16,25
2,g2,1,4,9,16,25
3,g3,1,4,9,16,25
4,g4,1,4,9,16,25
5,g5,1,4,9,16,25
6,g6,1,4,9,16,25
7,g7,1,4,9,16,25
8,g8,1,4,9,16,25